Custom src and iface
aviant-tech/libuavcan pull request #1
Opened 2023-10-31 12:45 UTC by oystub

Required changes for https://github.com/aviant-tech/PX4-Autopilot/pull/36 in order to send messages with a custom source node id and and interface mask.

2023-11-22 09:36 UTC, kibidev requested changes
The code seem fine, but I have some comments regarding branches.
I do not think we should merge to main, as this makes syncing the upstream repository harder. Create a new "aviant/main" branch or similar to use instead.
Possible, we should also maintain something like "aviant/python3.10-fix" as long as this is the branched used in PX4.

It would be worth trying to get this merged in upstream, so we have less to maintain.

2024-08-02 15:35 UTC, Torjusba approved these changes
Looks good to me. Consider handling the TODO comment, but it does not seem like it is important to do anything about

2024-08-02 15:35 UTC, Torjusba commented on libuavcan/src/transport/uc_transfer_sender.cpp
> +     * TODO: TID is not needed for anonymous transfers, this part of the code can be skipped?
TODO

2024-08-02 15:37 UTC, oystub commented on libuavcan/src/transport/uc_transfer_sender.cpp
> +     * TODO: TID is not needed for anonymous transfers, this part of the code can be skipped?
This todo comment was in the original code as well :joy:

2024-08-02 15:38 UTC, merged